// 塔罗牌图片CDN地址映射
export const tarotImageUrls = {
  // 大阿卡纳牌
  "愚人": "https://qiniustatic.wodidashi.com/TheFool.jpg",
  "魔法师": "https://qiniustatic.wodidashi.com/TheMagician.jpg",
  "女祭司": "https://qiniustatic.wodidashi.com/TheHighPriestess.jpg",
  "皇后": "https://qiniustatic.wodidashi.com/TheEmpress.jpg",
  "皇帝": "https://qiniustatic.wodidashi.com/TheEmperor.jpg",
  "教皇": "https://qiniustatic.wodidashi.com/TheHierophant.jpg",
  "恋人": "https://qiniustatic.wodidashi.com/TheLovers.jpg",
  "战车": "https://qiniustatic.wodidashi.com/TheChariot.jpg",
  "力量": "https://qiniustatic.wodidashi.com/Strength.jpg",
  "隐士": "https://qiniustatic.wodidashi.com/TheHermit.jpg",
  "命运之轮": "https://qiniustatic.wodidashi.com/WheelOfFortune.jpg",
  "正义": "https://qiniustatic.wodidashi.com/Justice.jpg",
  "倒吊人": "https://qiniustatic.wodidashi.com/TheHangedMan.jpg",
  "死神": "https://qiniustatic.wodidashi.com/Death.jpg",
  "节制": "https://qiniustatic.wodidashi.com/Temperance.jpg",
  "恶魔": "https://qiniustatic.wodidashi.com/TheDevil.jpg",
  "高塔": "https://qiniustatic.wodidashi.com/TheTower.jpg",
  "星星": "https://qiniustatic.wodidashi.com/TheStar.jpg",
  "月亮": "https://qiniustatic.wodidashi.com/TheMoon.jpg",
  "太阳": "https://qiniustatic.wodidashi.com/TheSun.jpg",
  "审判": "https://qiniustatic.wodidashi.com/Judgement.jpg",
  "世界": "https://qiniustatic.wodidashi.com/TheWorld.jpg",
  
  // 小阿卡纳牌 - 权杖
  "权杖Ace": "https://qiniustatic.wodidashi.com/AceOfWands.jpg",
  "权杖2": "https://qiniustatic.wodidashi.com/TwoOfWands.jpg",
  "权杖3": "https://qiniustatic.wodidashi.com/ThreeOfWands.jpg",
  "权杖4": "https://qiniustatic.wodidashi.com/FourOfWands.jpg",
  "权杖5": "https://qiniustatic.wodidashi.com/FiveOfWands.jpg",
  "权杖6": "https://qiniustatic.wodidashi.com/SixOfWands.jpg",
  "权杖7": "https://qiniustatic.wodidashi.com/SevenOfWands.jpg",
  "权杖8": "https://qiniustatic.wodidashi.com/EightOfWands.jpg",
  "权杖9": "https://qiniustatic.wodidashi.com/NineOfWands.jpg",
  "权杖10": "https://qiniustatic.wodidashi.com/TenOfWands.jpg",
  "权杖侍卫": "https://qiniustatic.wodidashi.com/PageOfWands.jpg",
  "权杖骑士": "https://qiniustatic.wodidashi.com/KnightOfWands.jpg",
  "权杖王后": "https://qiniustatic.wodidashi.com/QueenOfWands.jpg",
  "权杖国王": "https://qiniustatic.wodidashi.com/KingOfWands.jpg",
  
  // 小阿卡纳牌 - 圣杯
  "圣杯Ace": "https://qiniustatic.wodidashi.com/AceOfCups.jpg",
  "圣杯2": "https://qiniustatic.wodidashi.com/TwoOfCups.jpg",
  "圣杯3": "https://qiniustatic.wodidashi.com/ThreeOfCups.jpg",
  "圣杯4": "https://qiniustatic.wodidashi.com/FourOfCups.jpg",
  "圣杯5": "https://qiniustatic.wodidashi.com/FiveOfCups.jpg",
  "圣杯6": "https://qiniustatic.wodidashi.com/SixOfCups.jpg",
  "圣杯7": "https://qiniustatic.wodidashi.com/SevenOfCups.jpg",
  "圣杯8": "https://qiniustatic.wodidashi.com/EightOfCups.jpg",
  "圣杯9": "https://qiniustatic.wodidashi.com/NineOfCups.jpg",
  "圣杯10": "https://qiniustatic.wodidashi.com/TenOfCups.jpg",
  "圣杯侍卫": "https://qiniustatic.wodidashi.com/PageOfCups.jpg",
  "圣杯骑士": "https://qiniustatic.wodidashi.com/KnightOfCups.jpg",
  "圣杯王后": "https://qiniustatic.wodidashi.com/QueenOfCups.jpg",
  "圣杯国王": "https://qiniustatic.wodidashi.com/KingOfCups.jpg",
  
  // 小阿卡纳牌 - 宝剑
  "宝剑Ace": "https://qiniustatic.wodidashi.com/AceOfSwords.jpg",
  "宝剑2": "https://qiniustatic.wodidashi.com/TwoOfSwords.jpg",
  "宝剑3": "https://qiniustatic.wodidashi.com/ThreeOfSwords.jpg",
  "宝剑4": "https://qiniustatic.wodidashi.com/FourOfSwords.jpg",
  "宝剑5": "https://qiniustatic.wodidashi.com/FiveOfSwords.jpg",
  "宝剑6": "https://qiniustatic.wodidashi.com/SixOfSwords.jpg",
  "宝剑7": "https://qiniustatic.wodidashi.com/SevenOfSwords.jpg",
  "宝剑8": "https://qiniustatic.wodidashi.com/EightOfSwords.jpg",
  "宝剑9": "https://qiniustatic.wodidashi.com/NineOfSwords.jpg",
  "宝剑10": "https://qiniustatic.wodidashi.com/TenOfSwords.jpg",
  "宝剑侍卫": "https://qiniustatic.wodidashi.com/PageOfSwords.jpg",
  "宝剑骑士": "https://qiniustatic.wodidashi.com/KnightOfSwords.jpg",
  "宝剑王后": "https://qiniustatic.wodidashi.com/QueenOfSwords.jpg",
  "宝剑国王": "https://qiniustatic.wodidashi.com/KingOfSwords.jpg",
  
  // 小阿卡纳牌 - 星币
  "星币Ace": "https://qiniustatic.wodidashi.com/AceOfPentacles.jpg",
  "星币2": "https://qiniustatic.wodidashi.com/TwoOfPentacles.jpg",
  "星币3": "https://qiniustatic.wodidashi.com/ThreeOfPentacles.jpg",
  "星币4": "https://qiniustatic.wodidashi.com/FourOfPentacles.jpg",
  "星币5": "https://qiniustatic.wodidashi.com/FiveOfPentacles.jpg",
  "星币6": "https://qiniustatic.wodidashi.com/SixOfPentacles.jpg",
  "星币7": "https://qiniustatic.wodidashi.com/SevenOfPentacles.jpg",
  "星币8": "https://qiniustatic.wodidashi.com/EightOfPentacles.jpg",
  "星币9": "https://qiniustatic.wodidashi.com/NineOfPentacles.jpg",
  "星币10": "https://qiniustatic.wodidashi.com/TenOfPentacles.jpg",
  "星币侍卫": "https://qiniustatic.wodidashi.com/PageOfPentacles.jpg",
  "星币骑士": "https://qiniustatic.wodidashi.com/KnightOfPentacles.jpg",
  "星币王后": "https://qiniustatic.wodidashi.com/QueenOfPentacles.jpg",
  "星币国王": "https://qiniustatic.wodidashi.com/KingOfPentacles.jpg",
  
  // 牌背
  "cardBack": "https://qiniustatic.wodidashi.com/CardBack.jpg"
}; 